<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test websocket</title>
</head>
<body>
<div id="msg"></div>
<input type="text" id="text">
<input type="submit" value="发送数据" onclick="sending()">
</body>
<script>
    var msg = document.getElementById("msg");
    var wsServer = 'ws://localhost:9501';
    //调用 websocket 对象建立连接：
    //参数：ws/wss(加密)：//ip:port （字符串）
    var websocket = new WebSocket(wsServer);
    //onopen 监听连接打开
    websocket.onopen = function (evt) {
        //websocket.readyState 属性：
        /*
         CONNECTING    0    The connection is not yet open.
         OPEN    1    The connection is open and ready to communicate.
         CLOSING    2    The connection is in the process of closing.
         CLOSED    3    The connection is closed or couldn't be opened.
         */
        console.log(websocket.readyState);
    };

    function sending() {
        var text = document.getElementById('text').value;
        document.getElementById('text').value = '';
        //向服务器发送数据
        websocket.send(text);
    }
    //监听连接关闭
    websocket.onclose = function (evt) {
        msg.innerHTML+="Disconnected<br>";
    };

    //onmessage 监听服务器数据推送
    websocket.onmessage = function (evt) {
        msg.innerHTML += evt.data + '<br>';
        console.log('Retrieved data from server: ' + evt.data);
    };
    //监听连接错误信息
    websocket.onerror = function (evt, e) {
        console.log('Error occured: ' + evt.data);
    };

</script>
</html>